### ISSUE TITLE
compile error with Arduino

### ISSUE THREAD

**Issue by Cubyte** [MartyMacGyver/ESP32-Digital-RGB-LED-Drivers#12]
just hoping anyone can point out what i doing wrong or failed to install.
my issue is i get an error in 2 lines of code in the ws2812.cpp file

DPORT_SET_PERI_REG_MASK(DPORT_PERIP_CLK_EN_REG, DPORT_RMT_CLK_EN);
DPORT_CLEAR_PERI_REG_MASK(DPORT_PERIP_RST_EN_REG, DPORT_RMT_RST);

if i // the code it will compile but won't run

**Comment by MartyMacGyver** [comment]
Are you fully up to date on your Arduino-ESP32 installation? Which commit are you based on?

**Comment by MartyMacGyver** [comment]
If you managed to resolve this yourself let me know.

**Comment by Cubyte** [comment]
thanks I updated the arduino ide and esp ide which sorted out the problem .
now it works great thanks for your hard work and great support
