### ISSUE TITLE
idf example on a .c file

### ISSUE THREAD

**Issue by LEMAOR** [MartyMacGyver/ESP32-Digital-RGB-LED-Drivers#14]
Any reason the example is a .cpp file? i been learning on my own idf and all that i have done is on a c files, would it be posible to release an exampl on how to use this library on c?

**Comment by MartyMacGyver** [comment]
The old example was written to maximize the ability to use it with both Arduino-ESP32 and ESP-IDF without changes. The library itself is in flux and undergoing an overhaul, but it's written in C++. Not sure how a pure C example would work with that.

That said, I'll add it to my list of things to consider.
