### ISSUE TITLE
Consider separating the component from the example for easier importing

### ISSUE THREAD

**Issue by lukecyca** [MartyMacGyver/ESP32-Digital-RGB-LED-Drivers#23]
Components should be organized such that they can be included in others' projects using `git submodule`. I have had to [fork this](https://github.com/lukecyca/ESP32-Digital-RGB-LED-Drivers) so that I can submodule it into my projects.

**Comment by MartyMacGyver** [comment]
This project serves as an Arduino-ESP32 library as well as an IDF component, using the same code base (via copying, which avoids the problem of handling symlinks, which would be a problem particularly on Windows).

Personally I'd prefer one common code base feeding both, perhaps via a submodule itself, but I'm not sure that'll work right on either side. Thoughts?

**Comment by MartyMacGyver** [comment]
I'm closing this out - the code base is being rewritten as a more Arduino-like library and with minimal effort it could be included in an esp-idf project (though I haven't done a lot on the esp-idf side of this except to remove all the duplicate copies of the code). I don't plan to remodel this further to specifically map to the esp-idf component structure.
