### ISSUE TITLE
DPORT function update

### ISSUE THREAD

**Issue by spencerhochberg** [MartyMacGyver/ESP32-Digital-RGB-LED-Drivers#8]
`  SET_PERI_REG_MASK(DPORT_PERIP_CLK_EN_REG, DPORT_RMT_CLK_EN);
  CLEAR_PERI_REG_MASK(DPORT_PERIP_RST_EN_REG, DPORT_RMT_RST);`

in ws2812_init should be updated to:

`
  DPORT_SET_PERI_REG_MASK(DPORT_PERIP_CLK_EN_REG, DPORT_RMT_CLK_EN);
  DPORT_CLEAR_PERI_REG_MASK(DPORT_PERIP_RST_EN_REG, DPORT_RMT_RST);
`

after a recent esp-idf update

**Comment by MartyMacGyver** [comment]
Thanks for the tip! I'll look into that soon.

**Comment by MartyMacGyver** [comment]
It should be working now for the Arduino and esp-idf versions
