### ISSUE TITLE
Doesn't work with current IDF

### ISSUE THREAD

**Issue by paulo-raca** [MartyMacGyver/ESP32-Digital-RGB-LED-Drivers#9]
With current versions of IDF, there isn't any output on the pin.

I've identified the problem to be on https://github.com/espressif/esp-idf/commit/17747b33586075e46cadfe0c096dabb7f1a80df2 -- Reverting it makes the leds blink again :)

I would love to submit a PR, but I really haven't figured out those IO matrixes yet, so I'm hoping you can work a proper fix.

Thank you!

**Comment by MartyMacGyver** [comment]
That's weird - I haven't used it in a while but odds are it's something in my code. I assume it was the IDF driver you were testing - the Arduino one probably has the same issue.

I'll give it a try when time permits and see if I can see what's going on.

**Comment by paulo-raca** [comment]
Neither the IDF or the Arduino versions work out of the box.

I managed to get the IDF version working by reverting that commit.

**Comment by MartyMacGyver** [comment]
Well, hopefully it's fixable. I will look at it as time permits, though the next week or so it going to be unusually busy here.

**Comment by MartyMacGyver** [comment]
Followup: I'm able to delve into the issue now. I'll update you when I (or ESP) figures something out. I'm hoping it'll be a straightforward fix by either myself or in the IDF.

**Comment by MartyMacGyver** [comment]
This auto-closed with my commit, but if it's still not working for you let me know

**Comment by MartyMacGyver** [comment]
As I haven't heard from you but this seems to have resolved the main problem and worked for others similarly affected I'm going to close this out.

**Comment by paulo-raca** [comment]
It took me a while, but I have tested it and works perfectly.

Thank you!

**Comment by MartyMacGyver** [comment]
I'm glad to hear it! Thanks for your help tracking down that commit!
